### ISSUE TITLE
Change loggig style

### ISSUE THREAD

**Issue by Unaimend** [Unaimend/msb_gapseq_pipeline#4]
# Use log style from silvio https://github.com/Waschina/gapsnake/blob/main/workflow/rules/recon.smk

**Comment by Porthmeus** [comment]
Use the "log:" variable in the rules and pipe the output into these files

**Comment by Unaimend** [comment]
Yes, I'd like to discuss this. Why should one do this? My settings profile already creates a folder with logs. Why do you pipe this manually @Porthmeus
